{
  description = "A simple NixOS flake config";

  inputs = {
    # NixOS 官方软件源，这里使用 nixos-25.05 分支
    nixpkgs.url = "github:NixOS/nixpkgs/nixos-25.05";
    nixos-wsl.url = "github:nix-community/NixOS-WSL/main";
    nix-ld.url = "github:nix-community/nix-ld";
    # this line assume that you also have nixpkgs as an input
    nix-ld.inputs.nixpkgs.follows = "nixpkgs";
    home-manager.url = "github:nix-community/home-manager";
        helix.url = "github:helix-editor/helix/master";
  };

  outputs =
    {
      self,
      nixpkgs,
      nixos-wsl,
      nixos-hardware,
      nix-ld,
      ...
    }@inputs:
    {
      nixosConfigurations.wsl = nixpkgs.lib.nixosSystem {
        system = "x86_64-linux";
        modules = [
          ./wsl/init.nix
          nixos-wsl.nixosModules.default
          {
            system.stateVersion = "25.05";
            wsl.enable = true;
          }
        ];
      };
      # Alias for `nixos` hostname generated by default.
      nixosConfigurations.nixos = self.nixosConfigurations.wsl;
    };
}
